version: '3'

services:
  discord-bot:
    container_name: discord-bot
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/usr/src/app/data
